### PR TITLE
SHARE-414 Project visibility gets updated only after confirmation

### PR DESCRIPTION
**Pull request by maxfazeli-dev**
The AJAX call now gets executed after the user has made a decision in the confirmation dialog.

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing (CI), if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
- [x] Check that your pull request has been successfully deployed to https://web-test-1.catrob.at/

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

### CODE REVIEW

**Review by IsolatedSys — APPROVED** [review]

**Review by IsolatedSys — APPROVED** [review]
does what it's supposed to do

**Review by dmetzner — CHANGES_REQUESTED** [review]
Please add tests for this behavior.

**Comment by maxfazeli-dev** [comment]
> Please add tests for this behavior.

There are already tests for this in "profile_edit.feature" (line 189). Should we add more?

**Comment by IsolatedSys** [comment]
a testcase were you decline the message so that the project is still visible would be nice (the error we had before u fixed it)

**Comment by maxfazeli-dev** [comment]
All test passed, 2 new tests added, should be ready for merge

**Review by dmetzner — APPROVED** [review]

**Pull request merged**
