### PR TITLE
SHARE-251 Refactoring - Adminarea - Users | Users

### PR DESCRIPTION
**Pull request by IsolatedSys**
More filters (createdAt, group, enabled, mail),
ConfigureListFields method to edit shown list,
removed impersonate user
removed mosaic view
tests

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

### CODE REVIEW

**Review by hebesempso — APPROVED** [review]
The changes look good!

**Review by dmetzner — CHANGES_REQUESTED** [review]
updating a user with invalid credentials just crashes.
E.g username already exists

Users will never be able to fill 'profile' with useful data. Should we just remove it? @HCrane 
image

keys & social are maybe interesting for the future. Should we keep them?  @HCrane 
image

Same applies to the show view.

image

It would be nice if we could add an option to directly switch between enabled/disabled directly in the list view. Since that is the only action that is really used sometimes.

**Comment by IsolatedSys** [comment]
Should I remove the profile page or do you want to keep it?

**Comment by dmetzner** [comment]
@HCrane your call

In my opinion, it can be removed

**Comment by HCrane** [comment]
@HaraldKoinig you can remove the Profile and the Social sections. We will keep the Keys sections for now :)

**Comment by IsolatedSys** [comment]
I removed the profile and social area in the edit/show forms and you can switch enabled/disabled in the listview.
Also there is no exception when entering a username or email which is already in use. But the header shows the wrong username afterwards. I tried my best (also with @FelixAuf 's help) to fix this but it's a problem of sonata.

**Comment by dmetzner** [comment]
That "problem" with the header is such a minor detail + it is in the admin interface. Pretty sure no one will ever see it ;)

The Feature itself looks nice - please just fix the remaining failing test cases.

**Review by dmetzner — APPROVED** [review]

**Pull request merged**
