### PR TITLE
SHARE-129 Redesign of Notifications

### PR DESCRIPTION
**Pull request by leno12**
- Notifications separeted and redesigned (old, new)
- X button to delete notification added
- Delete all Button added
- Dropdown for notifications in the  menu added containing subsections to filter notifications
- Behat Testcase added
- Old testcases refactored

### CODE REVIEW

**Review by HCrane — CHANGES_REQUESTED** [review]
Primarily the code is fine and as requested by our PO but there are some things that need fixing before the PR can be merged:

- The dropdown menu in the sidebar does not work for me (grunted multiple times) -> please check.
- When there are no notifications please do not show the red dot. The user should be alerted if there are notifications, if there are none no need to notify the user ;) 
Screenshot_5
- There are some codestyle errors in the `.php` files you changed. Please see if you can fix them (at least the errors please) For a codestyle report that only scans the files you touched you can use a command `bin/console phpcheckstyle <insert git commit hash here>` so for the commit in this PR you would write `056b6a736ebfdf45632d80121f9fae93f42adec1` you can find the `.html` report under `<catroweb main dir>/tests/style-report/index.html`. There is a small bug that the codechecker will also check the auto generated migrations file. You can happily ignore the codestyle in that file! :)

Tests:
These tests are failing on my dev vm but this dosent mean that your PR is the reason for it. We know that there are some kind of timing issues -> if it runs on your development maschine that is fine by me. Also please check if these tests fail on the current `develop` branch.

- [ ] `tests/behat/features/web/catro_notification.feature:21`
- [ ] `tests/behat/features/web/catro_notification.feature:62`
- [ ] `tests/behat/features/web/help.feature:70`
- [ ] `tests/behat/features/web/mediapackage.feature:30`
- [ ] `tests/behat/features/web/mediapackage.feature:53`
- [ ] `tests/behat/features/web/my_profile.feature:313`
- [ ] `tests/behat/features/web/my_profile.feature:344`
- [ ] `tests/behat/features/web/private_project.feature:53`
- [ ] `tests/behat/features/web/private_project.feature:63`
- [ ] `tests/behat/features/web/profile.feature:90`
- [ ] `tests/behat/features/web/program_debug_build.feature:56`
- [ ] `tests/behat/features/web/program_remixes.feature:92`
- [ ] `tests/behat/features/web/program_remixes.feature:122`
- [ ] `tests/behat/features/web/program_remixes.feature:130`
- [ ] `tests/behat/features/web/search.feature:17`
- [ ] `tests/behat/features/web/search.feature:21`
- [ ] `tests/behat/features/web/search.feature:25`
- [ ] `tests/behat/features/web/search.feature:43`
- [ ] `tests/behat/features/web/search_programs_via_extensions.feature:34`
- [ ] `tests/behat/features/web/search_programs_via_tags.feature:21`
- [ ] `tests/behat/features/web/search_programs_via_tags.feature:32`
- [ ] `tests/behat/features/web/visited_programs.feature:22`

**Comment by leno12** [comment]
Hi regarding the dropdown and red dots.
Database needs to be updated so  php bin/console make:migration needs to be executed and grunt after that.
After that the dropdown should work and red dots should dissapear and testcases that are related to notifications should pass.
Regarding other testcases and codestyle i will check that and fix it tomorrow.

**Comment by HCrane** [comment]
If you create migrations please use the command `bin/console doctrine:migrations:diff` command. It parses the `ORM`-Annotations and creates a new migration file as make:migration does. This is the only reason i can think of why, if I use this command it creates a new migration file with the migrations you have in yours again. but the problem persists because I did reset my install completetly(so it will be on the newest migration) and grunted and it does still show the red dot and the dropdown does not work.

**Comment by leno12** [comment]
Hi i created a new diff for migrations I hope it will work now. And the red dots also should  not be visible when user doesn't have new notifications.
And i fixed some codestyle errors.
It is passing all testcases for me except 4 which are also not working on develop branch.

**Review by HCrane — APPROVED** [review]

**Review by HCrane — CHANGES_REQUESTED** [review]
- Dropdwon works as expected now! :)
Screenshot_6
- Please remove this file: `src/Migrations/2019/Version20190911130007.php` since it is not needed anymore.
- Optional: there are still some easy to fix codestyle-errors in the file `src/Catrobat/Controller/Web/UserNotificationController.php` (strict comparison operator `!=` -> `!==`) if you got the time please fix them!

Edit: Please rebase the branch onto the current `develop` branch too!

**Review by HCrane — APPROVED** [review]

**Pull request merged**
