### PR TITLE
SHARE-140 reset command enhancement

### PR DESCRIPTION
**Pull request by IsolatedSys**
The reset command is more natural now. It creates multiple users who randomly follow each other and randomly generates comments,
likes, downloads, reported and featured projects (currently screenshots are used for featured projects)

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
For featured projects the screenshots of the projects are used.

### Tests - additional information
Reset command has no tests as far as I know

### CODE REVIEW

**Comment by dmetzner** [comment]
While implementing SHARE-211 https://github.com/Catrobat/Catroweb-Symfony/pull/443
I had to fix multiple permission problems. I think it would be nice if you could also add my `docker/app/prepare-test-env` script in the reset command. Or it might be better if you directly execute the `docker/app/set-test-permissions` commands in the reset command. And add grunt too. The rest should already be in the reset command.

Then there is no need to do those things by hand anymore.

**Comment by IsolatedSys** [comment]
You mean that I just should execute the .sh file /docker/app/test-permissions.sh through the reset command?
Also grunt is already in this .sh file.

**Comment by dmetzner** [comment]
Option 1:
take the commands I use in those 2 scripts but are missing in reset command and execute them one by one in the reset command. 

Option 2:
remove the commands that are both in the reset command and the script. And just execute the script. The script at least up to now is not providing a detailed output if something failed. (+ is not merged)

**Review by dmetzner — CHANGES_REQUESTED** [review]
**Please rebase to the current develop branch.** 

I like the new reset command(s). It is definitely a big enhancement. Therefore I would say the PR can be merged when it is rebased.

Still, some things that should be added in the future. But that can be done in a separate PR.

- create all associated notifications when creating comments, reactions, follows, ...
  mark only some of them as read, deleted.
- add remix projects
- add scratch projects
- permission commands

**Review by dmetzner — APPROVED** [review]

**Pull request merged**
