### PR TITLE
SHARE-244 Refactoring - Adminarea - Featured Urls

### PR DESCRIPTION
**Pull request by FelixAuf**
Featured Programs can now be added by their URL in the FeaturedProgramAdmin page. When adding a new featured project, you can enter either the project ID or its url in the new field "Program Id or Url". This is done by removing everything but the ID from the project URL. The FeaturedUrlAdmin was deleted as there is no need for it anymore. Also added tests for the new functionality. Removed "url" column from the "featured" table.

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

### CODE REVIEW

**Review by dmetzner — APPROVED** [review]

**Review by leno12 — CHANGES_REQUESTED** [review]
I am not sure if you should remove the url and do that search just by ID. As far as I know we need to be able to add some urls to the Featured Slider. For example just like we have on the share.catrob.at url to discord. But you can ask seniors about that just to be sure.
Another thing would be nice if you could somehow prevent the crashing of the website when the wrong id is entered or the wrong url.

**Comment by FelixAuf** [comment]
> I am not sure if you should remove the url and do that search just by ID. As far as I know we need to be able to add some urls to the Featured Slider. For example just like we have on the share.catrob.at url to discord. But you can ask seniors about that just to be sure.
> Another thing would be nice if you could somehow prevent the crashing of the website when the wrong id is entered or the wrong url.

@leno12 I talked to @HCrane about removing the URL and he was okay with it. But that makes sense and it would be no Problem to add back the URL, maybe with a Checkbox if it should be saved as an URL or as the Project ID. I will look into preventing the crash as well!

**Comment by leno12** [comment]
Well checkbox would be nice.
If you cant do something because of the sonata framework just say

**Comment by FelixAuf** [comment]
> Well checkbox would be nice.
> If you cant do something because of the sonata framework just say

@leno12 Implemented your suggestions, there is now a checkbox to decide if you want to use the url or id. Also prevented the crash, the "validate" function in Sonata Admin is very useful for that

**Comment by leno12** [comment]
@FelixAuf  Validation  for the ID looks nice and adding Featured program using ID is working perfectly. But if I try to add URL the website crashes with the following error "Call to a member function getId() on null" . And please if you could also add validation for the URL, to check if URL is valid for example with filter_var or some regex that would be also nice.
And don't forget to rebase

**Review by dmetzner — CHANGES_REQUESTED** [review]
like @leno12 said ;)

**Comment by FelixAuf** [comment]
@leno12 @dmetzner the crash shouldn't happen anymore, although I could not always reproduce it for some reason. Also added a filter_var to validate the URL like you said :)

**Review by dmetzner — CHANGES_REQUESTED** [review]
Updating a featured project (id) to be a featured URL seems to work in the admin interface, but the feature banner on the homepage is ignoring the URL and redirects a user to the old project id instead of the URL. Try to get rid of the old project id in a featured project on successful updates.

**Comment by FelixAuf** [comment]
@dmetzner I now remove the program from the featured project if a url is added and vice versa so that problem should be solved!

**Review by dmetzner — APPROVED** [review]

**Pull request merged**
